In [3]:
import tensorflow as tf
import numpy as np

In [31]:
x_dims = 3
batch_size = 4
x_val = np.random.randint(0, 10, (batch_size, x_dims))
x = tf.placeholder(tf.float32, (None, x_dims))
w = tf.Variable(tf.constant([[1], [2], [3]], dtype=tf.float32))

In [32]:
tf.matmul(x, w).get_shape()

TensorShape([Dimension(None), Dimension(1)])

In [38]:
y = tf.squeeze(tf.matmul(x, w))

grad_x, grad_w = tf.gradients(y, [x, w])

with tf.Session() as sess:
    sess.run(w.initializer)
    y_val, grad_x, grad_w = sess.run([y, grad_x, grad_w], {x:x_val})

    print('x = \n', x_val)
    print('y = \n', y_val)
    print('dy/dx = \n', grad_x)
    print('dy/dw = \n', grad_w)

x = 
 [[8 1 0]
 [2 8 9]
 [8 8 8]
 [7 1 7]]
y = 
 [10. 45. 48. 30.]
dy/dx = 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
dy/dw = 
 [[25.]
 [18.]
 [24.]]


In [39]:
y = tf.reduce_sum(tf.squeeze(tf.matmul(x, w)))

grad_x, grad_w = tf.gradients(y, [x, w])

with tf.Session() as sess:
    sess.run(w.initializer)
    y_val, grad_x, grad_w = sess.run([y, grad_x, grad_w], {x:x_val})

    print('x = \n', x_val)
    print('y = \n', y_val)
    print('dy/dx = \n', grad_x)
    print('dy/dw = \n', grad_w)

x = 
 [[8 1 0]
 [2 8 9]
 [8 8 8]
 [7 1 7]]
y = 
 133.0
dy/dx = 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
dy/dw = 
 [[25.]
 [18.]
 [24.]]
